language: android
dist: trusty
android:
  components:
    - build-tools-29.0.3
    - android-29

script:
  - ./gradlew clean :silentorderpost:clean :silentorderpost:assembleRelease

deploy:
  provider: script
  script: ./gradlew :silentorderpost:bintrayUpload
  on:
    branch: master